# Scraping Huizenzoeker.nl to Analyse the Dutch Housing Market

Here we import both datasets in the form of CSV files from RStudio after they have been modified to work like real datasets (e.g. adjusting variable classes from character to numeric, and fixing the thousands/decimals delimiters).

In [2]:
#Importing the needed packages
import pandas as pd

**Municipality-level dataset**

In [3]:
huizenzoeker = pd.read_csv('huizenzoeker_data2.csv', encoding= 'latin-1') #Adding the latin encoding solved the UNICODE error

In [4]:
huizenzoeker = pd.DataFrame(huizenzoeker)
huizenzoeker

,Province,City,gem_vraagprijs,perc_ver_vraagprijs,verk_woningen,perc_ver_verkocht,gem_m2prijs,perc_ver_m2prijs,perc_overboden,perc_ver_overboden,best_inkomen,n_inwoners,perc_pop_stijging,perc_pop_daling
0,Noord-Holland,Aalsmeer,685000.0,57.47,12,-7.69,4476.0,9.22,10.67,3.42,45800.0,31859,0.41,NaN
1,Noord-Holland,Alkmaar,362500.0,25.00,38,-39.68,3926.0,10.62,14.05,1.43,36300.0,109436,0.81,NaN
2,Noord-Holland,Amstelveen,570000.0,18.13,21,-56.25,4724.0,1.88,305.01,296.30,37800.0,91675,0.92,NaN
3,Noord-Holland,Amsterdam,450000.0,7.78,230,-27.44,6961.0,5.90,16.10,0.37,30100.0,872757,1.13,NaN
4,Noord-Holland,Beemster,612000.0,-12.26,4,-33.33,4311.0,-6.89,-0.23,-12.10,47300.0,10022,2.81,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,Limburg,ValkenburgaandeGeul,365000.0,-5.19,4,-55.56,3308.0,9.75,12.60,5.41,35600.0,16367,NaN,0.63
348,Limburg,Venlo,319000.0,16.00,32,-50.00,2727.0,17.80,7.84,-0.72,33700.0,101802,0.20,NaN
349,Limburg,Venray,297000.0,8.99,8,-33.33,2729.0,23.09,8.98,1.22,39100.0,43614,0.66,NaN
350,Limburg,Voerendaal,287500.0,-11.13,2,-75.00,2185.0,-12.53,7.69,-2.09,40800.0,12475,0.18,NaN
351,Limburg,Weert,350000.0,21.53,21,-30.00,2799.0,-9.62,8.19,-0.35,37300.0,50105,0.53,NaN

In [6]:
huizenzoeker.describe() #to return the summary statisitics for all municipalities in the Netherlands. 
#look whether these statistics seem realistic/right due to the thousands and decimal separator problem we faced.

,gem_vraagprijs,perc_ver_vraagprijs,verk_woningen,perc_ver_verkocht,gem_m2prijs,perc_ver_m2prijs,perc_overboden,perc_ver_overboden,best_inkomen,n_inwoners,perc_pop_stijging,perc_pop_daling
count,3.520000e+02,341.000000,352.000000,346.000000,352.000000,341.000000,348.000000,346.000000,349.000000,352.000000,292.000000,59.000000
mean,3.690349e+05,9.909560,18.127841,-22.113699,3133.180614,3.972903,13.985144,4.637139,40037.535817,49282.267045,0.800925,0.340678
std,1.549829e+05,28.825046,26.904773,52.621778,1020.587474,13.924234,45.292619,45.529907,4728.094766,73491.321323,0.678329,0.372331
min,0.000000e+00,-40.860000,0.000000,-100.000000,0.000000,-34.770000,-6.470000,-13.400000,25400.000000,0.000000,0.000000,0.010000
25%,2.950000e+05,-8.160000,6.000000,-52.222500,2603.250000,-4.780000,7.935000,-0.770000,36900.000000,21680.500000,0.340000,0.150000
50%,3.500000e+05,4.520000,11.000000,-33.330000,3081.500000,3.040000,10.290000,0.925000,40400.000000,30790.500000,0.630000,0.260000
75%,4.180000e+05,21.180000,19.250000,-3.965000,3601.250000,10.500000,12.957500,2.867500,43500.000000,49697.250000,1.102500,0.425000
max,1.695000e+06,149.630000,230.000000,325.000000,9059.000000,96.890000,788.890000,782.810000,53800.000000,872757.000000,5.430000,2.550000

**Province-level dataset**

In [7]:
huizenzoeker_province = pd.read_csv('huizenzoeker_province_data1.csv', encoding= 'latin-1')

In [8]:
huizenzoeker_province = pd.DataFrame(huizenzoeker_province)
huizenzoeker_province

,Province,gem_vraagprijs,perc_ver_vraagprijs,verk_woningen,perc_ver_verkocht,gem_m2prijs,perc_ver_m2prijs,perc_overboden,perc_ver_overboden,best_inkomen,n_inwoners,perc_pop_stijging
0,Noord-Holland,425000.0,13.33,976,-24.75,4437,9.53,28.66,16.00,36200,2879527,0.92
1,Zuid-Holland,365000.0,7.67,1283,-38.14,3602,5.54,20.98,10.76,35800,3708696,0.95
2,Zeeland,280000.0,1.82,168,-38.91,2676,5.31,10.05,1.92,36900,383488,0.12
3,Noord-Brabant,350000.0,3.24,738,-46.83,3197,5.37,8.74,0.87,38100,2548585,0.71
4,Utrecht,425000.0,9.25,608,-8.30,4190,4.05,13.03,1.06,39500,1354834,0.94
5,Flevoland,339000.0,4.31,153,-39.53,2982,1.64,16.40,1.69,39500,423021,1.55
6,Friesland,285000.0,3.64,322,-12.74,2429,-1.82,11.71,1.07,34900,649957,0.35
7,Groningen,250000.0,11.11,316,-9.20,2550,6.65,20.27,4.51,30600,540009,0.38
8,Drenthe,309000.0,4.75,236,-25.55,2481,1.31,11.58,1.09,37100,493682,0.31
9,Overijssel,300000.0,1.69,457,-16.15,2692,4.42,10.50,0.66,36900,1162406,0.52
10,Gelderland,350000.0,4.48,748,-31.56,3119,2.16,13.94,3.39,37500,2085952,0.67
11,Limburg,285000.0,3.64,376,-38.06,2482,5.80,42.52,33.65,34800,1117201,0.10

In [9]:
huizenzoeker_province.describe()

,gem_vraagprijs,perc_ver_vraagprijs,verk_woningen,perc_ver_verkocht,gem_m2prijs,perc_ver_m2prijs,perc_overboden,perc_ver_overboden,best_inkomen,n_inwoners,perc_pop_stijging
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,1.200000e+01,12.000000
mean,330250.000000,5.744167,531.750000,-27.476667,3069.750000,4.163333,17.365000,6.389167,36483.333333,1.445613e+06,0.626667
std,55959.603936,3.740944,349.086372,13.318931,681.205632,2.965414,9.787681,9.803833,2394.627826,1.109205e+06,0.419227
min,250000.000000,1.690000,153.000000,-46.830000,2429.000000,-1.820000,8.740000,0.660000,30600.000000,3.834880e+05,0.100000
25%,285000.000000,3.540000,296.000000,-38.332500,2533.000000,2.030000,11.310000,1.067500,35575.000000,5.284272e+05,0.340000
50%,324000.000000,4.395000,416.500000,-28.555000,2837.000000,4.865000,13.485000,1.805000,36900.000000,1.139804e+06,0.595000
75%,353750.000000,8.065000,740.500000,-15.297500,3298.250000,5.605000,20.447500,6.072500,37650.000000,2.201610e+06,0.925000
max,425000.000000,13.330000,1283.000000,-8.300000,4437.000000,9.530000,42.520000,33.650000,39500.000000,3.708696e+06,1.550000